---
- hosts: server
  become: yes
  user: root

  roles:
    - nginx
    - php
    - { role: geerlingguy.mysql } # This role is now setting up MySQL and users
    - mysql # This role is fixing Craft CMS v2 MySQL bug
    - libs
    - firewall
    - users

