---
- name: Enable Firewall
  ufw: state=enabled policy=allow

- name: Allow SSH access
  ufw: rule=allow port=22

- name: Allow port 80
  ufw: rule=allow port=80

- name: Allow port 443 https
  ufw: rule=allow port=443

- name: Allow port 3306 mysql
  ufw: rule=allow port=3306

- name: Allow port 25 smtp
  ufw: rule=allow port=25

- name: Reject Default Policy
  ufw: state=enabled policy=reject

- name: Reload nginx
  service: name=nginx state=reloaded