---
- name: Fix Craft CMS MySQL Group By issue
  lineinfile:
      dest=/etc/mysql/my.cnf
      regexp="^sql_mode"
      line="sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      insertafter="^\[mysqld\]"
      state=present
  notify: restart mysql
