---
# - name: Set MySQL root password before installing
#   debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'

# - name: Confirm MySQL root password before installing
#   debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'

- name: Install MySQL
  apt: pkg=mysql-server state=latest update_cache=true

- name: Install Python MySQLdb module
  apt: name=python-mysqldb state=present

- name: Create MySQL User
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} priv=*.*:ALL state=present

- name: Removes all anonymous user accounts
  mysql_user: name='' host=localhost state=absent

- name: Removes root user access
  mysql_user: name='root' host=localhost state=absent
